spring:
  config:
    activate:
      on-profile: me
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  datasource:
    url: jdbc:mariadb://localhost:3306/nalbangPlatform
    driver-class-name: org.mariadb.jdbc.Driver
    username: {{DB_USERNAME}}
    password: {{DB_PASSWORD}}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG