###
POST {{backend_api}}/graphql
Content-Type: application/graphql

mutation {
  createUser(request: {
    name: "hello",
    age: "10"
  }
  ) {
  id
  name
  age
}
}

###
POST {{backend_api}}/graphql
Content-Type: application/graphql

query {
    user(id: 1) {
        id
        name
        age
    }
}

###
POST {{backend_api}}/graphql
Content-Type: application/graphql

mutation {
  createBoard(request: {
    title: "title~",
    content: "content~"
    userId: 1
  }
  ) {
  id
  title
  content
  userId
}
}

###
POST {{backend_api}}/graphql
Content-Type: application/graphql

query {
    board(id: 1) {
        id
        title
        content
        userId
    }
}