### file upload
POST {{backend_api}}/api/v1/image/upload?imageType=PLATFORM_TEST
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.png"

< /Users/tnswh/Desktop/1.png
--WebAppBoundary--